### ISSUE TITLE
epi2me labs launcher installation error

### ISSUE THREAD

**Issue by zat89** [epi2me-labs/labslauncher#4] opened 2020-10-25 02:04 UTC
Hi,

I have installed successfully epi2me-labs launcher v 0.6.1 and server v 0.2.5 previously. After read the newly instruction that we have to move into jupyterlab, i try to install epi2me-labs-launcher v 0.6.5.
But, i got some error. When i try to install via debian distribution (18.04 ubuntu version), i got this error when i executed /usr/local/bin/EPI2ME-Labs-Launcher/EPI2ME-Labs-Launcher :

    AttributeError: Can't get attribute 'NotebookFlavour' on <module 'labslauncher' 
    from '/usr/local/bin/EPI2ME-Labs-Launcher/labslauncher/__init__.pyc'>
    The above exception was the direct cause of the following exception:
    Traceback (most recent call last):
      File "build/EPI2ME-Labs-Launcher/labslauncher-script.py", line 2, in <module>
      File "labslauncher/app.py", line 791, in main
        settings = Settings(labslauncher.Defaults())
      File "labslauncher/qtext.py", line 176, in __init__
        prev_version = self.qsettings.value("version", None)
    SystemError: <built-in method value of QSettings object at 0x7f00864f0b88> 
    returned a result with an error set
    [10919] Failed to execute script labslauncher-script

After that, i tried to install via github. After i ran PYTHON=python3 make run, i got the similar error from above :

Finished processing dependencies for labslauncher==0.6.4
AttributeError: Can't get attribute 'NotebookFlavour' on <module 'labslauncher' from '/home/zat/Software/labslauncher/labslauncher/__init__.py'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zat/Software/labslauncher/venv/bin/labslauncher", line 11, in <module>
    load_entry_point('labslauncher', 'console_scripts', 'labslauncher')()
  File "/home/zat/Software/labslauncher/labslauncher/app.py", line 791, in main
    settings = Settings(labslauncher.Defaults())
  File "/home/zat/Software/labslauncher/labslauncher/qtext.py", line 176, in __init__
    prev_version = self.qsettings.value("version", None)
SystemError: <built-in method value of QSettings object at 0x7f489a2e54c0> returned a result with an error set
Makefile:67: recipe for target 'run' failed
make: *** [run] Error 1

Thanks for your help.

**Comment by cjw85** [comment] 2020-10-26 11:13
Hi @zat89,

We still cannot reproduce this error. Can you run the following in the directory where you have cloned the repository:

```
. venv/bin/activate
python --version
pip freeze
```
and report the output here.

**Comment by callumparr** [comment] 2020-10-31 14:26
I have the same issue when installing via apt install with Ubuntu 18.04. Previously could install 0.6.4 version with no issues.

**Comment by cjw85** [comment] 2020-12-04 13:24
Hi @zat89,

My colleague @sagrudd has work through this with @callumparr and found a solutionin his case. Can you try moving the files `~/.config/EPI2ME Labs/Launcher.conf` and `~/.config/QtProject.conf` to a backup location and rerunning the EPI2MELabs Launcher?

**Comment by cjw85** [comment] 2021-02-01 09:23
I'm closing this on the assumption that issues have been resolved.

**Closed by cjw85** 2021-02-01 09:23 UTC
