### ISSUE TITLE
failure to launch due to nextflow issue with latest v2.0.1

### ISSUE THREAD

**Issue by callumparr** [epi2me-labs/labslauncher#27] opened 2022-03-02 05:31 UTC
Running latest ont-epi2melabs installed via apt-get and making sure nextflow is available in PATH by cp the binary from my $HOME to /usr/local/bin which is in PATH

```
❯ nextflow -v
nextflow version 21.10.6.5660
```

I can start, update control epi2melabs with `labsmanager` but using `labslauncher` I get issues with nextflow directory. Please see below the error log:

```
❯ labslauncher
[14:23:44 - labslauncher] Starting application.
[14:23:45 - DckrClnt] Creating docker client with options:
           image name: ontresearch/epi2melabs-notebook
           server name: Epi2Me-Labs-Server-minion
           data bind: /epi2melabs/
           command: start-notebook.sh  --NotebookApp.port_retries=0 --no-browser --notebook-dir=/
           host only: True
           wf_schema_dir: /epi2me-resources/workflows/
           wf_base_dir: /epi2melabs//nextflow
           fixed tag: None
           proxies: None
[14:23:45 - DckrClnt] Connection to docker (re)established.
[14:23:48 - Launcher] Status changed: 'unknown'->'running'
[14:23:48 - Launcher] Found running container, synchronising workflow server port.
[14:23:48 - Launcher] Starting workflow server.
Traceback (most recent call last):
  File "labslauncher-script.py", line 2, in <module>
  File "labslauncher/app.py", line 1224, in launcher_main
  File "labslauncher/app.py", line 881, in __init__
  File "labslauncher/app.py", line 974, in start_workflow_server
  File "labslauncher/workflows.py", line 58, in make_server
  File "epi2melabs/workflows/launcher.py", line 89, in __init__
  File "epi2melabs/workflows/launcher.py", line 437, in get_or_create_dir
NotADirectoryError: [Errno 20] Not a directory: '/home/minion/nextflow/instances'

```

**Comment by cjw85** [comment] 2022-03-18 09:25
Hi again!

This is a known issue that should be fixed in the most recent version.

It is caused by the fact that the application attempts to create a directory `~/nextflow` for storing workflow results. But cunningly our help documentation for installation nextflow instructs people to copy the nextflow program to `~/nextflow` hence labslauncher gets a bit confused!

**Comment by cjw85** [comment] 2022-05-05 20:30
This has been resolved

**Closed by cjw85** 2022-05-05 20:30 UTC
